defaults: &defaults
  adapter: mysql
  pool: 5
  timeout: 5000
  host: localhost
  username: gnomeslab
  password: gnomes1234

test: &test
  database: archive_tree_test
  <<: *defaults

cucumber:
  <<: *test