defaults: &defaults
  adapter: mysql
  pool: 5
  timeout: 5000
  host: localhost
  username: your_application_specific_username
  password: your_application_specific_password

test: &test
  database: archive_tree_test
  <<: *defaults

cucumber:
  <<: *test